language: java
jdk:
  - oraclejdk8

install: ant

script:
  - ant test
  - ant integracion-continua

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - nacho.chiappe@gmail.com
      - franco.choquescipione@gmail.com
      - julimuchi@gmail.com
      - ramaa196@gmail.com
    on_failure: always
